Default: &defaults
  user: foo
  password: RUs}4f3(X[bkFCn{
  #host: centrinia.ddns.net
  host: localhost
  port: 5432
  database: Foo
  poolsize: 10

Development:
  <<: *defaults
  host: centrinia.ddns.net

Testing:
  database: Foo_test
  <<: *defaults

Staging:
  database: Foo_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Foo
  poolsize: 100
  <<: *defaults
