Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://centrinia.ddns.net:3000"
  approot: ""
  copyright: Copyright 2014. All your base are belong to us.
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  approot: "http://centrinia.ddns.net"
  port: 80
  <<: *defaults
